export const APIROUTE = process.env.REACT_APP_APIROUTE
export const IP_ADDRESS_API = process.env.REACT_APP_IP_ADDRESS_API
export const NUMBER_PER_PAGE = process.env.REACT_APP_NUMBER_PER_PAGE
export const UPLOAD_MAX_SIZE = process.env.REACT_APP_UPLOAD_MAX_SIZE
export const FACEBOOK_APP_ID = process.env.REACT_APP_FACEBOOK_APP_ID
export const GOOGLE_CLIENT_ID = process.env.REACT_APP_GOOGLE_CLIENT_ID
export const TWITCH_CLIENT_ID = process.env.REACT_APP_TWITCH_CLIENT_ID
export const INSTAGRAM_CLIENT_ID = process.env.REACT_APP_INSTAGRAM_CLIENT_ID

export const CONTACT_EMAIL = process.env.REACT_APP_CONTACT_EMAIL
export const GOOGLE_CAPTCHA_KEY = process.env.REACT_APP_GOOGLE_CAPTCHA_KEY

export const RAFFLEE_TWITTER_LINK = process.env.REACT_APP_RAFFLEE_TWITTER_LINK
export const RAFFLEE_FACEBOOK_LINK = process.env.REACT_APP_RAFFLEE_FACEBOOK_LINK
export const RAFFLEE_INSTAGRAM_LINK = process.env.REACT_APP_RAFFLEE_INSTAGRAM_LINK
export const RAFFLEE_LINKEDIN_LINK = process.env.REACT_APP_RAFFLEE_LINKEDIN_LINK
export const RAFFLEE_TIKTOK_LINK = process.env.REACT_APP_RAFFLEE_TIKTOK_LINK

export const LANGUAGE_NAME = {
  en: "english",
  fr: "french"
}