const images = {
    google_icon: require('../assets/image/google_icon.png'),
    fb_icon: require('../assets/image/google_icon.png'),
    twitter_icon: require('../assets/image/twitter_icon.png'),
    twitch_icon: require('../assets/image/twitch_icon.png'),
    youtube_icon: require('../assets/image/youtube_icon.png'),
    instagram_icon: require('../assets/image/instagram_icon.png'),
    logo: require('../assets/image/logo.png'),
    logout_icon: require('../assets/image/logout_icon.png'),
    profile_img: require('../assets/image/profile_img.png'),
    star: require('../assets/image/star.svg'),
    trans_star: require('../assets/image/trans_star.svg'),
    user_icon: require('../assets/image/user_icon.png'),
    logout_icon: require('../assets/image/logout_icon.png'),
    my_campaign: require('../assets/image/my_campaign.svg'),
    my_campaign_blue: require('../assets/image/my_campaign_blue.svg'),
    my_bills: require('../assets/image/my_bills.svg'),
    my_bills_blue: require('../assets/image/my_bills_blue.svg'),
    my_analytics: require('../assets/image/my_analytics.svg'),
    my_analytics_blue: require('../assets/image/my_analytics_blue.svg'),
    loading_icon: require('../assets/image/loading.gif'),
    video_player: require('../assets/image/video_player.png'),
}

export default images;