const images = {
    google_icon: require('../assets/image/google_icon.png'),
    fb_icon: require('../assets/image/google_icon.png'),
    twitter_icon: require('../assets/image/twitter_icon.png'),
    twitch_icon: require('../assets/image/twitch_icon.png'),
    youtube_icon: require('../assets/image/youtube_icon.png'),
    instagram_icon: require('../assets/image/instagram_icon.png'),
    logo: require('../assets/image/logo.png'),
    logout_icon: require('../assets/image/logout_icon.png'),
    profile_img: require('../assets/image/profile_img.png'),
    star: require('../assets/image/yellow_star.svg'),
    trans_star: require('../assets/image/trans_star.svg'),
    trans_star_favorite: require('../assets/image/trans_star_favorite.svg'),
    user_icon: require('../assets/image/user_icon.png'),
    company_icon: require('../assets/image/company_icon.svg'),
    my_campaign: require('../assets/image/my_campaign.svg'),
    my_campaign_blue: require('../assets/image/my_campaign_blue.svg'),
    my_bills: require('../assets/image/my_bills.svg'),
    my_bills_blue: require('../assets/image/my_bills_blue.svg'),
    my_analytics: require('../assets/image/my_analytics.svg'),
    my_analytics_blue: require('../assets/image/my_analytics_blue.svg'),
    inventory_icon: require('../assets/image/inventory.svg'),
    inventory_icon_blue: require('../assets/image/inventory_blue.svg'),
    ph_icon: require('../assets/image/ph.svg'),
    ph_icon_blue: require('../assets/image/ph_blue.svg'),
    following_icon: require('../assets/image/star.svg'),
    following_icon_blue: require('../assets/image/star_blue.svg'),
    my_circle_icon: require('../assets/image/my_circle.svg'),
    my_circle_icon_blue: require('../assets/image/my_circle_blue.svg'),
    loading_icon: require('../assets/image/loading.gif'),
    video_player: require('../assets/image/video_player.png'),
    campaign: require('../assets/image/campaign.png'),
    award: require('../assets/image/award.png'),
    clock: require('../assets/image/clock.png'),
    user: require('../assets/image/user.png'),
    entry: require('../assets/image/entry.svg'),
    congratulation_item_img: require('../assets/image/congratulation_item_img.png'),
    gap_img: require('../assets/image/gap_image.png'),
}

export default images;